---
title: "Impulsividade"
author: "Emanuel Cordeiro"
date: "3/26/2023"
output: html_document
---

```{r}
library(readr)
library(psych)
library(lavaan)
library(stringr)
library(tidyverse)
library(readxl)
```

```{r}
df <- read_xlsx("Base de dados/Construção de Instrumentos 2022.2 (respostas).xlsx")
```

```{r}
# Renomear
df <- df %>% rename(TCLE = "Tendo em vista os itens acima apresentados, eu, de forma livre e esclarecida, manifesto meu consentimento para participar da pesquisa.")
```

```{r}
# TCLE
df$TCLE[df$TCLE == 'Concordo'] <- '1'
df$TCLE[df$TCLE == 'Não concordo'] <- '0'
```

```{r}
# Eliminação de negativos
df <- df %>% filter(TCLE==1) # Eliminação de não respondentes
```

```{r}
# saparando intrumetnos de impulsividade
df_impulsividade <- df[, 10:51]
```

```{r}
# Itens reduzidos
df_impulsividade_2 <- df_impulsividade %>% select(1,2,3,4,8,9,10,11,12,13,
                                                  14,15,18,19,22,23,24,26,
                                                  27,28,29,30,31,32,33,34,
                                                  36,38,39,41,42)
```

```{r}
# Teste do modelo com 3 fatores
im_efa_2 <- fa(df_impulsividade_2, nfactors = '3', cor='poly', 
             fm='wls', rotate = 'geominQ')

im_efa_2$e.values
im_efa_2$loadings %>% view()
```

```{r}
# Fator 1
# Item 7 é negativo
df_impulsividade_2 %>% select(3,5,7:11) %>% psych::omega()
df_impulsividade_2 %>% select(3,5,7:11) %>% psych::alpha(check.keys = TRUE)

# Fator 2
# Item 18 é negativo
df_impulsividade_2 %>% select(4,17,18,20:22,24,25,27:30) %>% psych::omega()
df_impulsividade_2 %>% select(4,17,18,20:22,24,25,27:30) %>% psych::alpha(check.keys = TRUE)

# Fator 3
df_impulsividade_2 %>% select(1:2,6,12:16,23,26) %>% psych::omega()
df_impulsividade_2 %>% select(1:2,6,12:16,23,26) %>% psych::alpha(check.keys = TRUE)
```

```{r}
# Inverter itens negativos
df_impulsividade_2$H_7 <- ifelse(df_impulsividade_2$`Costumo realizar minhas atividades sem perder o foco.` == 1, 5,
                                 ifelse(df_impulsividade_2$`Costumo realizar minhas atividades sem perder o foco.` == 2, 4,
                                        ifelse(df_impulsividade_2$`Costumo realizar minhas atividades sem perder o foco.` == 4, 2,
                                               ifelse(df_impulsividade_2$`Costumo realizar minhas atividades sem perder o foco.` == 5, 1, df_impulsividade_2$`Costumo realizar minhas atividades sem perder o foco.`))))

df_impulsividade_2$H_18 <- ifelse(df_impulsividade_2$`Em conversas com amigos, penso antes de falar.` == 1, 5,
                                 ifelse(df_impulsividade_2$`Em conversas com amigos, penso antes de falar.` == 2, 4,
                                        ifelse(df_impulsividade_2$`Em conversas com amigos, penso antes de falar.` == 4, 2,
                                               ifelse(df_impulsividade_2$`Em conversas com amigos, penso antes de falar.` == 5, 1, df_impulsividade_2$`Em conversas com amigos, penso antes de falar.`))))
```

```{r}
# Cálculo dos fatores de impulsividade
# Fator 1
df_impulsividade_2$F_IM1 <- df_impulsividade_2 %>% select(3,5,8:11,32) %>% rowMeans()

# Fator 2
df_impulsividade_2$F_IM2 <- df_impulsividade_2 %>% select(4,17,20:22,24,25,27:30,33) %>% rowMeans()

# Fator 3
df_impulsividade_2$F_IM3 <- df_impulsividade_2 %>% select(1:2,6,12:16,23,26) %>% rowMeans()
```

```{r}
# Copiando o banco df para df_geral, com a finalidade de salvar os escores dos fatores de impulsividade e CE
df_geral <- df
```

```{r}
df_CE <- read_csv("Base de dados/Escores Competências Emocionais.csv")
```

```{r}
df_geral <- bind_cols(df_geral, select(df_CE, "REO", "RESBP", "EE", "PE", "RESAP", "CEG"))
df_geral <- bind_cols(df_geral, select(df_impulsividade_2, "F_IM1", "F_IM2", "F_IM3"))
```












